server:
  ssl:
    key-store: "classpath:keystore.p12"
    key-store-type: PKCS12
    key-store-password: asdttycc
  port: 8443

spring :
  datasource:
    url: jdbc:mysql://yoondb.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/yoondb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # 실제 엔드포인트와 DB 이름
    username: admin   # 실제 사용자 이름
    password: uionrtqwe   # 실제 사용자 비번
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # 처음에는 create -> 나중에는 update
    show-sql: true

